### ISSUE TITLE
Script reports "domain is taken" 100% of the time.

### ISSUE THREAD

**Issue by ThisIsTenou** [baibhavanand/DAC#4] opened 2023-05-13 19:45 UTC
No matter which domain is being queried, the result is always for the default "aim.com"-domain.

![grafik](https://github.com/baibhavanand/DAC/assets/57889616/a5e975ea-cf81-4bc0-b1f8-299d3cb22a63)

Therefore, I am assuming that the API used is either defective or has been changed, making this script unusable.

Unfortunatly, I couldn't find documentation on the API used, else I would've suggested a fix.

**Comment by baibhavanand** [comment] 2023-05-15 21:22
Thanks @ThisIsTenou for pointing it out.
Yes, the API stopped working.
I'll push an update referencing this issue soon.

**Comment by baibhavanand** [comment] 2023-05-16 08:52
The issue is now fixed. Thank you for creating this issue.

**Closed as completed by baibhavanand** 2023-05-16 08:52 UTC
Labels: bug
